### ISSUE TITLE
plat.h: no such file

### ISSUE THREAD

**Issue by una-dinosauria** [mischasan/sse2#2]
Sorry,  C/make noob over here.

If I git clone your code and run `make`, I get the following error:

```
sseutil.c:1:18: fatal error: plat.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'sseutil.o' failed
make: *** [sseutil.o] Error 1
```

I'm guessing I have to download other libraries to run your code. Could you please give me some pointers to those?

**Comment by mischasan** [comment]
So sorry; plat.h is one of a set of tools headers I litter my projects with.
plat.h is in https://github.com/mischasan/util  (for one).
My humble apologies ... sse2 was sort of an orphan, put there to provide example code for some blog posts.
If you see anything interesting, I will update it with something more up-to-date.
Recently I've been using SSE2 for faster charset conversion (UTF16->CP1252 etc).

**Comment by una-dinosauria** [comment]
Thanks for your response, Mischa,
I have checked your blog, and the stand-alone version on https://mischasan.wordpress.com/2011/10/03/the-full-sse2-bit-matrix-transpose-routine/ works great for me.
Cheers,
